name: merge language-files from dev into main

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  cherrypick-files:
    runs-on: ubuntu-latest

    steps:
      - name: checkout dev
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: check if language-files have been changed in dev
        id: check-changes
        run: |
          set -x
          language_files=("public/locales/de/common.json" "public/locales/en/common.json" "public/locales/fr/common.json")
          changes=()
          
          for file in "${language_files[@]}"; do
            if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- "$file" | grep -q "$file"; then
              changes+=("$file")
              echo "$file has been changed"
            fi
          done

          if [ ${#changes[@]} -eq 0 ]; then
            echo "no changes detected"
          fi
          
          echo "changes=${changes[*]}" >> $GITHUB_ENV

      - name: merge changes into main
        if: env.changes != ''
        run: |
          git checkout main
          for file in ${{ env.changes }}; do
            git cherry-pick ${{ github.sha }} -- "$file"
          done
          
          git commit -m 'language file(s) changed'
          git push origin main
